In [3]:
!pip install pymysql

Requirement already satisfied: pymysql in /usr/local/lib/python3.10/dist-packages (1.1.0)

In [13]:
import pymysql
import pandas as pd

In [47]:
trashcan = pd.read_csv('./광산구_쓰레기통.csv', encoding='cp949')

trashcan.drop(['연번', ' 관리번호', ' 도로명', '행정동', ' 설치주소', ' 세부위치', ' 수거쓰레기종류', ' 쓰레기통종류', ' 관리기관명', ' 관리기관전화번호', ' 데이터기준일자'], axis=1, inplace=True)

mydb = pymysql.connect(
    host='database-plonit.clluyrc4oifq.ap-northeast-2.rds.amazonaws.com',
    user='plonit',
    password='flogging207',
    port=3306,
    db='plonit'
)

dbconn = mydb.cursor()

sql = 'INSERT INTO item_info (gugun_code, content_type, latitude, longitude) values (2920000000, true, %s, %s)'

for idx, row in trashcan.iterrows():
    dbconn.execute(sql, (row['위도'], row['경도']))

mydb.commit()
mydb.close()

In [48]:
trashcan = pd.read_csv('./서구_쓰레기통.csv', encoding='cp949')

trashcan.drop(['연번', '행정동', '설치주소', '세부위치', '수거쓰레기종류', '쓰레기통종류\t', '관리기관명', '관리기관전화번호'], axis=1, inplace=True)

mydb = pymysql.connect(
    host='database-plonit.clluyrc4oifq.ap-northeast-2.rds.amazonaws.com',
    user='plonit',
    password='flogging207',
    port=3306,
    db='plonit'
)

dbconn = mydb.cursor()

sql = 'INSERT INTO item_info (gugun_code, content_type, latitude, longitude) values (2914000000, true, %s, %s)'

for idx, row in trashcan.iterrows():
    dbconn.execute(sql, (row['위도'], row['경도']))

mydb.commit()
mydb.close()

In [52]:
trashcan = pd.read_csv('./동구_쓰레기통.csv', encoding='cp949')

trashcan.drop(['연번', '위치', '개수', '비고','데이터기준일자'], axis=1, inplace=True)

mydb = pymysql.connect(
    host='database-plonit.clluyrc4oifq.ap-northeast-2.rds.amazonaws.com',
    user='plonit',
    password='flogging207',
    port=3306,
    db='plonit'
)

dbconn = mydb.cursor()

sql = 'INSERT INTO item_info (gugun_code, content_type, latitude, longitude) values (2911000000, true, %s, %s)'

for idx, row in trashcan.iterrows():
    dbconn.execute(sql, (row['위도'], row['경도']))

mydb.commit()
mydb.close()